### ISSUE TITLE
camer is open , zxing is not start detect.

### ISSUE THREAD

**Issue by SalutXiaolu** [aryehsilver/QRCodeMAUIBlazorTest#1]
after running the camer in TestApp,   can\t  detect any code ,

**Comment by aryehsilver** [comment]
@SalutXiaolu this project was meant to show how to integrate the ZXing library into MAUI. Your issue sounds like one specific to the ZXing package. I suggest you open an issue with them [here](https://github.com/Redth/ZXing.Net.Maui/issues).
