### ISSUE TITLE
How to return the scanned value to the blazor page caller?

### ISSUE THREAD

**Issue by OskrLrba** [aryehsilver/QRCodeMAUIBlazorTest#2]
Hi @aryehsilver,
Thank you very much for your sample.

As my question says, How can I return the scanned values from NewPage1.xaml.cs to Index.razor?
Any help vwill be appreciated.
```
  protected void BarcodesDetected(object sender, BarcodeDetectionEventArgs e) {
    foreach (BarcodeResult barcode in e.Results) {
      Console.WriteLine($"Barcodes: {barcode.Format} -> {barcode.Value}");
    }
    //TODO: return result to Index.razor
  }
```

**Comment by aryehsilver** [comment]
@OskrLrba You can pass them back with parameters. I will try and add this to the repo when I get a chance.

**Comment by aryehsilver** [comment]
@OskrLrba I have updated the repo with an example (commit [46d0a98](https://github.com/aryehsilver/QRCodeMAUIBlazorTest/commit/46d0a98dfaa71a53117adb930bd71167381e75b6))

In short, you pass them back to the main page, then pass them in to Blazor with a parameter
```
rootComponent.Parameters = new Dictionary<string, object> {
      { "BarcodeResults", barcodeResults }
    };
```
This parameter is caught in the `Main.razor` which you can then pass down to your component using a `cascadingparameter`
